title:  wooyol
tagline:  pieces
author:
  name: 'wooyol'
  twitter: wooyol

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'pieces-1'

google-ID: 'UA-105223896-1'

menu:
# - {name: 'About', url: 'about.html'}
# - {name: 'Writing', url: 'writing.html'}
# - {name: 'Contact', url: 'contact.html'}

social:
- {icon: 'facebook', link: 'https://www.facebook.com/neolaocoon'}
- {icon: 'github', link: 'https://www.github.com/wooyol'}
# - {icon: 'envelope', link: 'mailto:animate.em.all@gmail.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
