title:  wooyol
tagline:  pieces
author:
  name: 'wooyol'
  twitter: wooyol

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'pieces-1'

google-ID: 'UA-105223896-1'

menu:
# - {name: 'list', uri: 'list.html'}

social:
- {icon: 'facebook', link: 'https://www.facebook.com/neolaocoon'}
- {icon: 'github', link: 'https://www.github.com/wooyol'}
